### PR TITLE
Plugin implementation

### PR DESCRIPTION
**Pull request by crhym3**
Using google.golang.org/cloud/storage package.

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM codewise, but how is it with the copyright @bradrydzewski?

**Comment by bradrydzewski** [comment]
LGTM

@crhym3 thanks for submitting this. love the built-in concurrency
@tboerger I'm ok with the copyright assignment as long as we have a liberal oss license which in this case we do :)

**Comment by gtaylor** [comment]
Nice! This is useful to us already!

**Comment by bradrydzewski** [comment]
fyi, this plugin is now published. docs at http://addons.drone.io/google_cloud_storage/

**Pull request merged**
