### PR TITLE
Makefile, gitignore and MAINTAINERS improvements

### PR DESCRIPTION
**Pull request by tboerger**
I have improved the Makefile to result in reproducable builds, I have replaced the build date with the commit short SHA. I have also updated the list of maintainers and the gitignore to ignore coverage   output.

### CODE REVIEW

**Comment by jackspirou** [comment]
LGTM

**Comment by tboerger** [comment]
@bradrydzewski drone doesn't fail because of this PR, it seems to be related to upstream changes. Should we merge and fix the tests with a followup PR as I don't really know where the issue comes from?

**Comment by tboerger** [comment]
LGTM

**Comment by jackspirou** [comment]
@tboerger and @bradrydzewski any thoughts if this is good to merge since the failure is due to upstream changes to the `main_test.go` file as @tboerger described above ?

**Comment by tboerger** [comment]
Failing tests are unrelated, merging it for now.

**Pull request merged**
